name: Arm_Hackathon_workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ðŸ§ª Test Flask
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      #- run: |
      #    cd backend
      #    python3 -m venv venv
      #    source venv/bin/activate
      #    pip install -r requirements.txt 
       #   python3 -m pytest test
       #   deactivate

  deploy:
    needs: build-test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Moving html to nginx dir
        run: |
          ls -a
          cd frontend
          npm ci
          npm run build
          ls -a
          sudo rm -rf /var/www/arm-frontend/dist
          sudo mv ./dist /var/www/arm-frontend

      - name: Build Backend 
        run:  |
          if [ "$(sudo docker ps -aq -f name=web_app_backend)" ]; then
            echo "Container exists â†’ stopping and removing..."
            sudo docker stop web_app_backend || true
            sudo docker rm -f web_app_backend || true
          else
            echo "Container does NOT exist â†’ continuing..."
          fi
          sudo docker builder prune -a
          sudo docker build -t web_app_backend -f Dockerfile.backend .
          sudo docker run --pid=host --privileged --add-host host.docker.internal:host-gateway -p 5000:5000 -d --name web_app_backend web_app_backend
         
